### ISSUE TITLE
How to use wineditline as alternative for readline/BSD editline?

### ISSUE THREAD

**Issue by Csega** [winlibs/wineditline#2]
Dear weltling,

thanks for your work, the wineditline library seems extremely useful, since neither GNU readline, nor BSD editline are easy to use in a Windows environment. I tried to use wineditline for a project (gnudatalanguage) to compile on Windows 10 (64-bit) with CMake (3.11.0-rc2), but it did not recognize wineditline as a substitute for GNU readline or BSD editline. Could you help me with this? As a first try, I just gave the path to the compiled library:
-DEDITLINEDIR=[...]/wineditline/build/src/MinSizeRel/

But it did not work. What do I do wrong?

**Comment by weltling** [comment]
@Csega heh, too late, but probably anyway. I'm not sure about your particular case and the build system. In a usual way, putting the library to be linked with and headers to be found by the compiler works fine and that's how we use it in PHP.

Thanks.

**Comment by Csega** [comment]
@weltling No problem, since then I learnt a lot about CMake, and the problem was solved. However, if nowadays you'll look here sometimes, I'll maybe have some questions. Don't you want to make your code to be compatible with [vcpkg](https://github.com/microsoft/vcpkg)? There is no editline alternative there yet. And it would be very useful. :)

**Comment by weltling** [comment]
@Csega thanks for coming back! Please be informed, that this repository is not the upstream project. The upstream project is located on Sourcefourge, as linked in the readme. The winlibs org only mirrors the sources to be used in PHP builds, some of those are reused by other projects. It is highly recommended to target upstream with any bugfixes/patches, as it makes a little sense to maintain patches in forked repos. At least in this case.

Thanks.

**Comment by Csega** [comment]
@weltling thanks for the info. I'll check the upstream project then. :)
