### ISSUE TITLE
VS16 has /DEFAULTLIB:"MSVCRTD" on windows.php.net

### ISSUE THREAD

**Issue by Jan-E** [winlibs/wineditline#5]
The downloads of wineditline-2.205 at https://windows.php.net/downloads/php-sdk/deps/vs16 contain a edit_a.lib with
`/DEFAULTLIB:"uuid.lib" /DEFAULTLIB:"uuid.lib" /DEFAULTLIB:"MSVCRTD" /DEFAULTLIB:"OLDNAMES"`
This ia triggering a conflicting a DEFAULTLIB warning when building PHP 7.4 release versions.
Please recompile with MSVCRT in stead of MSVCRTD.

**Comment by Jan-E** [comment]
@weltling @cmb69 
These are the scripts I used for a MSVCRT compilation:
```
if exist CMakeCache.txt del CMakeCache.txt
if exist CMakeFiles rd CMakeFiles /s /q
cmake -G "Visual Studio 16 2019" -A Win32 .
perl -pi.bak -e "s/\/ObjectFileName>/\/ObjectFileName><ProgramDataBaseFileName>\$\(OutDir)\$\(TargetName).pdb<\/ProgramDataBaseFileName>/gi" edit_a.vcxproj
msbuild Project.sln -t:Build -p:Configuration=RelWithDebInfo -p:Platform=Win32
```
and
```
if exist CMakeCache.txt del CMakeCache.txt
if exist CMakeFiles rd CMakeFiles /s /q
cmake -G "Visual Studio 16 2019" -A x64 .
perl -pi.bak -e "s/\/ObjectFileName>/\/ObjectFileName><ProgramDataBaseFileName>\$\(OutDir)\$\(TargetName).pdb<\/ProgramDataBaseFileName>/gi" edit_a.vcxproj
msbuild Project.sln -t:Build -p:Configuration=RelWithDebInfo -p:Platform=x64
```
To be executed in the wineditline\src directory. The pecl line is a adjustment of the Cmake generated (RelWithDebInfo) edit_a.vcxproj to make sure that edit_a.pdb is created alongside of edit_a.lib

**Comment by cmb69** [comment]
Indeed, a bad build. Thank for reporting!

**Comment by Jan-E** [comment]
Just wondering: I did not see a defaultlib warning in the snaps builds. Do they use other libs?

**Comment by cmb69** [comment]
Hmm, the warnings are there, e.g. in https://windows.php.net/downloads/snaps/php-7.4/r30de357/logs/make-nts-windows-vs16-x64-r30de357.txt (search for MSVCRTD).

**Comment by Jan-E** [comment]
OK. I must have been looking with my nose.

**Comment by cmb69** [comment]
The new packages (2.205-1) are now available.

**Comment by Jan-E** [comment]
Thx. But no need to replace my own compiled version ;-)
