### ISSUE TITLE
readline.h is missing an `extern "C" {`

### ISSUE THREAD

**Issue by hsjunnesson** [winlibs/wineditline#6]
Trying to include this in a cpp program won't work, because you've missed the opening

```C
#ifdef __cplusplus
extern "C" {
#endif
```

https://github.com/winlibs/wineditline/blob/320e15f4c647f814bd62245d4aff22f8deeed977/src/editline/readline.h#L116-L118

**Comment by NicolasIRAGNE** [comment]
Hello, this has been fixed in update 2.206, which is not in this repository, and I am not sure if it is being actively maintained or not.

You can find the update on the official SVN repository http://mingweditline.sourceforge.net/?Downloads

**Comment by cmb69** [comment]
This downstream repo has been updated to WinEditLine 2.206 quite a while ago.
